#!/bin/sh
# Authelia s6 service

echo "[INFO] Starting authelia..."

# Standard start command for authelia
exec /usr/local/bin/s6-notifyoncheck -c /healthz /usr/local/bin/s6-setuidgid bsd /app/authelia --config /config/authelia.yml
