ARG BASE_VERSION=15
FROM ghcr.io/daemonless/base:${BASE_VERSION}

ARG FREEBSD_ARCH=amd64
ARG PACKAGES="authelia"
ARG APP_VERSION="latest"

LABEL org.opencontainers.image.title="Authelia" \
      org.opencontainers.image.description="Authelia on FreeBSD." \
      org.opencontainers.image.source="https://github.com/daemonless/authelia" \
      org.opencontainers.image.url="https://authelia.org/" \
      org.opencontainers.image.licenses="Apache-2.0" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.upstream-mode=pkg \
      io.daemonless.category="Utilities" \
      io.daemonless.port="9091" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.packages="${PACKAGES}" \
      io.daemonless.wip="true"
      

# Install dependencies
RUN pkg update && \
    pkg install -y ${PACKAGES} && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

# Download and install authelia
#RUN fetch -qo /tmp/authelia.tar.gz "${DOWNLOAD_URL}" && 
#    mkdir -p /usr/local/share/authelia && 
#    tar -xzf /tmp/authelia.tar.gz -C /usr/local/share/authelia --strip-components=1 && 
#    rm /tmp/authelia.tar.gz && 
#    echo "${APP_VERSION}" > /app/version

# Copy root filesystem
COPY root/ /

# Set permissions
RUN chmod +x /etc/services.d/authelia/run /healthz

# Expose
EXPOSE 9091

# Volumes
VOLUME /config
