ARG BASE_VERSION=15
FROM ghcr.io/daemonless/base:${BASE_VERSION}

ARG FREEBSD_ARCH=amd64
ARG PACKAGES="authelia"

LABEL org.opencontainers.image.title="Authelia" \
      org.opencontainers.image.description="Authelia on FreeBSD." \
      org.opencontainers.image.source="https://github.com/daemonless/authelia" \
      org.opencontainers.image.url="https://authelia.org/" \
      org.opencontainers.image.licenses="Apache-2.0" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.upstream-mode=pkg \
      io.daemonless.category="Utilities" \
      io.daemonless.port="9091" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.packages="${PACKAGES}" \
      io.daemonless.wip="true"
      

# Install dependencies
RUN pkg update && \
    pkg install -y ${PACKAGES} && \
    pkg clean -ay && \
    mkdir -p /app && pkg info authelia | sed -n 's/.*Version.*: *//p' > /app/version && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

# Copy root filesystem
COPY root/ /

# Set permissions
RUN chmod +x /etc/services.d/authelia/run /healthz

# --- Expose (Injected by Generator) ---
{%- if ports %}
EXPOSE {{ ports | map(attribute='port') | join(' ') }}
{%- endif %}

# --- Volumes (Injected by Generator) ---
{%- if volumes %}
VOLUME {{ volumes | map(attribute='path') | join(' ') }}
{%- endif %}
