#!/bin/sh
# Daemonless healthcheck for authelia

# Standard Mode: Check /api/health or HTTP endpoint
status=$(fetch -qo - "http://127.0.0.1:9091/api/health" 2>/dev/null | jq -r .status)
if [ $? -eq 0 ]; then
    if [ "$status" == "OK" ]; then
      exit 0
    fi
fi

exit 1
