icon: ':simple-authelia:'
cit:
  compose: true
  mode: health
  port: 9099
  health: /api/health
build:
  pkg_name: authelia
  auto_version: true
  variants:
    - tag: latest
      containerfile: Containerfile
      default: true
    - tag: pkg
      containerfile: Containerfile.pkg
      args:
        BASE_VERSION: "15-quarterly"
      default: true
    - tag: pkg-latest
      containerfile: Containerfile.pkg
      args:
        BASE_VERSION: "15-latest"


  
