#!/bin/sh
# Initialize Authelia directories

# Ensure directories exist and have correct ownership
mkdir -p /config /data/certificates /data/assets
chown -R bsd:bsd /config /data

# Generate default config if missing
if [ ! -f /config/authelia.yml ]; then
    cp /app/config.template.yml /config/authelia.yml
    chown bsd:bsd /config/authelia.yml
fi
